name: test_sleep
on: push
jobs:
  test:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sleep
        run: |
          echo "Sleep 10s"
          sleep 10
          echo "Done"
